# Generated by Django 4.1 on 2022-09-06 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_leitura', '0002_rename_status_leituras_concluido_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leituras',
            name='Concluido',
        ),
        migrations.AddField(
            model_name='leituras',
            name='status',
            field=models.CharField(choices=[('N', 'Não lido'), ('L', 'Lendo'), ('C', 'Concluido')], default=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='leituras',
            name='genero',
            field=models.CharField(choices=[('F', 'Fantasia'), ('FC', 'Ficção científica'), ('D', 'Distopia'), ('AV', 'Ação e aventura'), ('H', 'Horror'), ('TS', 'Thriller e Suspense')], default=False, max_length=50),
        ),
    ]
