# Generated by Django 4.1.1 on 2022-09-13 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_leitura', '0004_alter_leituras_genero_alter_leituras_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leituras',
            name='dataInicio',
        ),
        migrations.RemoveField(
            model_name='leituras',
            name='dataTermino',
        ),
        migrations.AlterField(
            model_name='leituras',
            name='genero',
            field=models.CharField(choices=[('Fantasia', 'Fantasia'), ('Humor', 'Humor'), ('Literatura Brasileira', 'Literatura Brasileira'), ('Romance', 'Romance'), ('Autoajuda', 'Autoajuda'), ('Biografia', 'Biografia'), ('Ficção científica', 'Ficção científica'), ('Distopia', 'Distopia'), ('Ação e aventura', 'Ação e aventura'), ('Horror', 'Horror'), ('Thriller e Suspense', 'Thriller e Suspense')], default=False, max_length=50),
        ),
    ]
