# Generated by Django 4.1.1 on 2022-09-13 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_leitura', '0005_remove_leituras_datainicio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leituras',
            name='status',
            field=models.CharField(choices=[('Não iniciado', 'Não iniciado'), ('Não Concluido', 'Não Concluido'), ('Concluido', 'Concluido')], default=False, max_length=50),
        ),
    ]
