# Generated by Django 4.1.1 on 2022-09-13 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_leitura', '0006_alter_leituras_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leituras',
            name='status',
            field=models.CharField(choices=[('Não iniciado', 'Não iniciado'), ('Não Concluído', 'Não Concluído'), ('Concluído', 'Concluído')], default=False, max_length=50),
        ),
    ]
